### ISSUE TITLE
pnpm方式部署，可访问页面但回答报错

### ISSUE THREAD

**Issue by WaitRainbow** [xcatliu/chatgpt-next#59]
页面错误：
![image](https://user-images.githubusercontent.com/51317190/230780823-7f9be9c2-11ac-493f-89a1-e03f9dcdf279.png)

系统错误日志：
```
{ NEXT_OTEL_VERBOSE: undefined, NEXT_RUNTIME: 'edge' }
Error [TypeError]: fetch failed
    at context.fetch (file:///usr/local/src/chatgpt/chatgpt-next/node_modules/.pnpm/next@13.2.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/sandbox/context.js:167:38)
    at tL (file:///usr/local/src/chatgpt/chatgpt-next/.next/server/app/api/chat/route.js:13:21308)
    at <unknown> (file:///usr/local/src/chatgpt/chatgpt-next/.next/server/app/api/chat/route.js:13:17025)
    at AsyncLocalStorage.run (node:async_hooks:341:14)
    at e7.wrap (file:///usr/local/src/chatgpt/chatgpt-next/.next/server/app/api/chat/route.js:13:13865)
    at e7.wrap (file:///usr/local/src/chatgpt/chatgpt-next/.next/server/app/api/chat/route.js:13:13624)
    at <unknown> (file:///usr/local/src/chatgpt/chatgpt-next/.next/server/app/api/chat/route.js:13:16543)
    at AsyncLocalStorage.run (node:async_hooks:341:14)
    at eX.wrap (file:///usr/local/src/chatgpt/chatgpt-next/.next/server/app/api/chat/route.js:13:12701)
    at eX.wrap (file:///usr/local/src/chatgpt/chatgpt-next/.next/server/app/api/chat/route.js:13:12334)
```

**Comment by xcatliu** [comment]
最近重構過，再部署試試吧
